[package]
name = "tokio_basic_ws"
version = "1.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
futures = "0.3.31"
log = "0.4.25"
env_logger = "0.11.6"
